### ISSUE TITLE
Urgent: FlipCard size breaks with APEX 24.1

### ISSUE THREAD

**Issue by lktg** [grlicaa/flipcard#4]
Hello,

After OCI upgraded Oracle APEX to 24.1, the cards are not working as before. The card's size is now fully stretched to the size of the region, and it ignores the "Grid Column" property.

![image](https://github.com/user-attachments/assets/4776140f-1b7b-4a01-b17a-477b20892b3d)

Please advise.
Thanks
LK

**Comment by grlicaa** [comment]
Hi Lior,

I imagine you have tested this on Oracle APEX 24.1, right?
There is an error when rendering region, not all lines of templates are rendered. This is due to new functionality in Oracle APEX 24.1 inside a template-based plugin called "Report Container".

To avoid this error I've upgraded this plugin release to a new version 24.1.
So now in GIT, you can find 23.2 and 24.1 versions.

To upgrade just simply import and replace the current plugin.

I hope this solves your issue. 

Kind regards,
Andrej Grlica

**Comment by lktg** [comment]
@grlicaa 
Thank you very much! that solved the problem!

I love this plug-in.

Lior
